In [6]:
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt

# 6. Introducing eager execution [Giới thiệu về Eager Execution]
* Chúng ta dễ dàng thấy rằng quá là phiền phức mỗi khi chúng ta muốn visualize ra một graph, nào là phải tạo ra một session, `tf.reset_default_graph()` và phải xác định các placeholder. Nhưng với Eager execution thì chúng ta có thể loại bỏ đi mọi thứ trên.
* Đoạn code dưới đây là cách mà chúng ta lập trình từ chapter 1 tới giờ:

In [3]:
x = tf.constant(11)
y = tf.constant(11)
z = x*y

with tf.Session() as sess:
    print(sess.run(z))

121


* Nhưng với eager execution, chúng ta chỉ việc khai báo dòng ở đầu script và từ đây về sau chúng ta ko cần phải khai báo session để chạy như trc đây nữa:
  ```python
  tf.enable_eager_execution()
  ```

In [7]:
tf.enable_eager_execution()

In [4]:
x = tf.constant(11)
y = tf.constant(11)
z = x*y

print(z)

tf.Tensor(121, shape=(), dtype=int32)


* Bây giờ để lấy giá trị output, chúng ta có thể dùng dòng code dưới đây:

In [5]:
z.numpy()

121

# 7. Math operations in TensorFlow
* Bây giờ chúng ta sẽ tìm hiểu các phép tính trog TensorFlow thông qua eager execution mode:

In [18]:
x = tf.constant(np.arange(1, 4, dtype=np.float))
y = tf.constant(np.arange(3, 0, -1, dtype=np.float))

print("x: ", x.numpy())
print("y: ", y.numpy())

x:  [1. 2. 3.]
y:  [3. 2. 1.]


* Để thực hiện phép cộng hai số, dùng `tf.add()`

In [13]:
sum = tf.add(x, y)

sum.numpy()

array([4., 4., 4.])

* Để thực hiện phép trừ hai số, dùng `tf.subtract()`

In [14]:
difference = tf.subtract(x, y)

difference.numpy()

array([-2.,  0.,  2.])

* Để nhân bình thường hai số, dùng `tf.multiply()`

In [15]:
product = tf.multiply(x, y)

product.numpy()

array([3., 4., 3.])

* Để chia hai số dùng `tf.divide()`

In [19]:
division = tf.divide(x, y)

division.numpy()

array([0.33333333, 1.        , 3.        ])

* Dot product của hai số, thì làm như sau:

In [20]:
dot_product = tf.reduce_sum(tf.multiply(x, y))

dot_product.numpy()

10.0

* Tìm index của minimum và maximun element trong một vector bằng hàm `tf.argmin()` và `tf.argmax()`

In [21]:
x = tf.constant([10, 0, 13, 9, 9, 13])

print("Index of minimum element: ", tf.argmin(x).numpy())
print("Index of maximum element: ", tf.argmax(x).numpy())

Index of minimum element:  1
Index of maximum element:  2


* Dùng `tf.math.squared_difference(<x>, <y>)` để tính hiệu bình phương của hai số:
  $$\textbf{Squared difference }(x, y) = (x - y)^2$$

In [22]:
x = tf.Variable([1, 3, 5, 7, 11])
y = tf.Variable([1])

tf.math.squared_difference(x, y).numpy()

array([  0,   4,  16,  36, 100], dtype=int32)

* In kiểu dữ liệu như sau

In [23]:
x = tf.Variable(69)

print(x.dtype)

<dtype: 'int32'>


In [25]:
x = tf.Variable(np.arange(1, 4))

x.dtype

tf.int64

* Để chuyển đổi kiểu dữ liệu, dùng hàm `tf.cast()`

In [27]:
x = tf.Variable(np.arange(1, 4))
print("Before casting: ", x.dtype)

x = tf.cast(x, dtype=tf.float32)
print("After casting: ", x.dtype)

Before casting:  <dtype: 'int64'>
After casting:  <dtype: 'float32'>


* Để nối hai matrix

In [28]:
x = [[3, 6, 9], [7, 7, 7]]
y = [[4, 5, 6], [5, 5, 5]]

* ...
  * Nối theo dòng

In [29]:
tf.concat([x, y], 0).numpy()

array([[3, 6, 9],
       [7, 7, 7],
       [4, 5, 6],
       [5, 5, 5]], dtype=int32)

* ...
  * Nối theo cột

In [30]:
tf.concat([x, y], 1).numpy()

array([[3, 6, 9, 4, 5, 6],
       [7, 7, 7, 5, 5, 5]], dtype=int32)

* Để tạo một stack từ các thành phần của ma trận

In [31]:
x = [[3, 6, 9], [7, 7, 7]]

In [32]:
tf.stack(x, axis=1).numpy()

array([[3, 7],
       [6, 7],
       [9, 7]], dtype=int32)

* Tính mean bằng `reduce_mean()`

In [33]:
x = tf.Variable([[1., 5.], [2., 3.]])
x.numpy()

array([[1., 5.],
       [2., 3.]], dtype=float32)

* ...
  * Lúc này $\text{mean} = \dfrac{1.0 + 5.0 + 2.0 + 3.0}{4}$

In [35]:
print(tf.reduce_mean(x).numpy())
print(tf.reduce_mean(input_tensor=x).numpy())

2.75
2.75


* ...
  * Tính mean theo dòng, $\text{mean dòng 1} = \dfrac{1.0 + 5.0}{2}$, $\text{mean dòng 2} = \dfrac{2.0 + 3.0}{2}$

In [36]:
tf.reduce_mean(input_tensor=x, axis=0).numpy()

array([1.5, 4. ], dtype=float32)

* ...
  * Tính mean theo cột

In [37]:
tf.reduce_mean(x, axis=1, keepdims=True).numpy()

array([[3. ],
       [2.5]], dtype=float32)

In [38]:
tf.reduce_mean(x, axis=1).numpy()

array([3. , 2.5], dtype=float32)

* Random các giá trị theo một phân phối xác suất nào đó

In [39]:
tf.random.normal(shape=(3, 2), mean=10.0, stddev=2.0).numpy()

array([[12.1354685,  5.3779345],
       [11.619761 ,  9.7982025],
       [ 8.976714 , 10.248131 ]], dtype=float32)

In [40]:
tf.random.uniform(shape=(3, 2), minval=0, maxval=None, dtype=tf.float32).numpy()

array([[0.15728581, 0.21118307],
       [0.33489215, 0.6082493 ],
       [0.82520115, 0.42798138]], dtype=float32)

* Tính toán hàm xác suất softmax<br>
  ![](./images/02.11.jpeg)

In [41]:
x = tf.constant([1.3, 5.1, 2.2, 0.7, 1.1])

tf.nn.softmax(x).numpy()

array([0.02019046, 0.90253764, 0.04966053, 0.01108076, 0.01653055],
      dtype=float32)

* Để tính toán gradient, chúng ta cần làm vài bước sau:
  * Định nghĩa một hàm `square` như sau, nó đơn giản là một hàm $y = x^2$. <br>
    ![](./images/02.12.jpg)

In [42]:
def square(x):
    return tf.multiply(x, x)

* ...
  * Gradient của hàm `square()` có thể dc tính bằng cách sử dụng hàm `tf.GradientTape()` như sau:

In [53]:
with tf.GradientTape(persistent=True) as tape:
    print(square(6.).numpy())

36.0
